name: Bug report and feature request
description: Report a bug or a feature request
title: "<Please write a comprehensive title>"
labels: [ 00 - Bug ]

body:
    -   type: markdown
        attributes:
            value: >
                If you have encountered a problem while using icclim or you would like to suggest a change,
                you can create an issue by filling the fields below.

    -   type: textarea
        attributes:
            label: "icclim/Python version information"
            description: >
                Please enter the versions of icclim and python you are currently using.
                You can find them with:
                ```
                import sys
                import icclim

                print(sys.version)
                print(icclim.__version__)
                ```
        validations:
            required: true

    -   type: textarea
        attributes:
            label: "Describe your issue"
        validations:
            required: true

    -   type: textarea
        attributes:
            label: "Minimal reproductible example"
            description: >
                For bugs, a minimal reproductible example is necessary for us to help you fix your issue.
            placeholder: |
                import icclim
                # fill with the code producing the bug
            render: python
        validations:
            required: false

    -   type: textarea
        attributes:
            label: "Error message:"
            description: >
                If any the code produce an error, please enter the full stacktrace here.
            placeholder: |
                << Enter the full error here (not just the ending message)>>
            render: shell
        validations:
            required: false
