# Conda environment for icclim development
name: icclim
channels:
 - conda-forge
 - defaults
dependencies:
 - python>=3.8
 - xclim>=0.33
 - numpy>=1.21.1
 - xarray>=0.19
 - dask[array]>=2021.10.0
 - netCDF4>=1.5.7
 - cftime>=1.5.0
 - pre-commit
 - pydata-sphinx-theme
 - pylint
 - pytest
 - sphinx
 - black
 - flake8
 - isort
