# Conda environment for icclim development
name: icclim
channels:
 - conda-forge
 - defaults
dependencies:
 # Core dependencies
 - python=3.8
 - xclim
 - numpy
 - xarray
 - dask
 - netCDF4
 - pyyaml
 # Dev dependencies
 - black
 - flake8
 - isort
 - pip
 - pre-commit
 - pylint
 - pytest
 - pytest-cov
 - setuptools
 # Extra dependencies
 - matplotlib
 - cartopy
