# Conda environment for icclim development
name: icclim
channels:
 - conda-forge
 - defaults
dependencies:
 - xclim>=0.30
 - numpy>=1.16
 - xarray>=0.17
 - dask>=2.6.0
 - netCDF4>=1.5.7
 - pyyaml>=6.0
 - pre-commit
 - pydata-sphinx-theme
 - pylint
 - pytest
 - sphinx
 - black
 - flake8
 - isort
