name: ci-build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # lint is handled by pre-commit ci conf
  test:
    # TODO add code coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install pytest
      run: pip install pytest
    - name: run unit tests
      run: pytest
