name: ci-build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # lint is handled by pre-commit ci conf
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pytest
        run: pip install pytest
      - name: Install pytest-cov
        run: pip install pytest-cov
      # Todo replace all those install by install from requirements.txt
      - name: Install pandas # todo removed once 1.4 is fixed
        run: pip install pandas==1.3.5
      - name: Install xarray
        run: pip install xarray
      - name: Install xclim
        run: pip install xclim
      - name: Install icclim
        run: python -m pip install -e .
      - name: Build coverage file
        run: |
            pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app icclim/tests/unit_tests | tee pytest-coverage.txt
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./../pytest-coverage.txt
          title: Report
          badge-title: Coverage
          hide-badge: false
          hide-report: false
          create-new-comment: false
          hide-comment: false
          report-only-changed-files: false
          junitxml-path: ./../pytest.xml
          junitxml-title: My JUnit Xml Summary Title
